api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView)
from . import views


app_name = 'api'

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(),
         name='token_refresh'),
    path('', views.getRoutes, name='routes'),
    path('projects/', views.getProjects, name='projects'),
    path('projects/<int:pk>/', views.getProject, name='project'),
    path('projects/<int:pk>/vote/', views.projectVote, name='project_vote'),
    path('removetag/', views.removeTag, name='remove_tag'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls', namespace='projects')),
    path('', include('users.urls', namespace='users')),
    path('api/', include('api.urls', namespace='api')),
    path('reset_password/',
         auth_views.PasswordResetView.as_view(
             template_name='reset_password.html'),
         name='reset_password'),
    path('reset_password_sent/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name='reset_password_sent.html'),
         name='passowrd_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='reset.html'),
         name='passowrd_reset_confirm'),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='passowrd_reset_complete.html'),
         name='passowrd_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from . import views


app_name = 'projects'

urlpatterns = [
    path('', views.projects, name='projects'),
    path('project/<str:pk>/', views.project, name='project'),
    path('create/', views.createProject, name='create_project'),
    path('update/<str:pk>/',
         views.updateProject, name='update_project'),
    path('delete/<str:pk>/',
         views.deleteProject, name='delete_project'),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>/', views.userProfile, name='user_profile'),
    path('register/', views.registerUser, name='register'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('account/', views.userAccount, name='account'),
    path('edit/', views.editAccount, name='edit_account'),
    path('create/skill/', views.createSkill, name='create_skill'),
    path('update/skill/<str:pk>/', views.updateSkill, name='update_skill'),
    path('delete/skill/<str:pk>/', views.deleteSkill, name='delete_skill'),
    path('inbox/', views.inbox, name='inbox'),
    path('message/<str:pk>/', views.viewMessage, name='view_message'),
    path('create/message/<str:pk>/', views.createMessage,
         name='create_message'),
]

projects/models.py
import uuid
from django.db import models
from users.models import Profile


class Project(models.Model):
    owner = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(
        upload_to='project/%Y/', default='default.jpg', null=True, blank=True)
    demoLink = models.CharField(max_length=2000, null=True, blank=True)
    sourceLink = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    voteTotal = models.IntegerField(default=0, null=True, blank=True)
    voteRatio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    class Meta:
        ordering = ('-voteRatio', '-voteTotal', 'title')

    def __str__(self):
        return self.title

    @property
    def imageUrl(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list('owner__id', flat=True)
        return queryset

    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()

        ratio = (upVotes / totalVotes) * 100
        self.voteTotal = totalVotes
        self.voteRatio = ratio

        self.save()


class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote')
    )
    owner = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    class Meta:
        unique_together = [['owner', 'project']]

    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.name
        return self.name

users/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    username = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=500, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    shortIntro = models.CharField(max_length=200, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='users/%Y/',
                              default='profiles/user-default.png',
                              null=True, blank=True)
    socialGithub = models.CharField(max_length=200, null=True, blank=True)
    socialtwitter = models.CharField(max_length=200, null=True, blank=True)
    sociallinkedin = models.CharField(max_length=200, null=True, blank=True)
    socialYoutube = models.CharField(max_length=200, null=True, blank=True)
    socialWebsite = models.CharField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return str(self.user.username)

    @property
    def imageUrl(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class Skill(models.Model):
    owner = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)


class Message(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    recipient = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, related_name='messages', null=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=500, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    isRead = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    class Meta:
        ordering = ('isRead', '-created')

    def __str__(self):
        return self.subject

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Skill, Message


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'email', 'username', 'password1', 'password2')
        lables = {
            'first_name': 'Name',
        }

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('name', 'username', 'email', 'location', 'shortIntro', 'bio',
                  'image', 'socialGithub', 'socialtwitter', 'sociallinkedin',
                  'socialYoutube', 'socialWebsite')

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = ('name', 'description')

    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ('name', 'email', 'subject', 'body')

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from .models import Profile
from .forms import CustomUserCreationForm, ProfileForm, SkillForm, MessageForm
from .utils import searchProfiles, paginateProfiles


def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            messages.success(request, 'User account was created!')

            login(request, user)
            return redirect('users:edit_account')

        else:
            messages.success(
                request, 'An error has occurred during registration!')

    context = {'page': page, 'form': form}
    return render(request, 'users/login_register.html', context)


def loginUser(request):
    page = 'login'

    if request.user.is_authenticated:
        return redirect('users:profiles')
    if request.method == "POST":
        username = request.POST['username'].lower()
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Username does not exist!')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(
                request.GET['next'] if 'next' in request.GET else 'users:account')

        else:
            messages.error(request, 'Username OR password is incorrect!')

    return render(request, 'users/login_register.html')


def logoutUser(request):
    logout(request)
    messages.info(request, 'User was logged out!')
    return redirect('users:login')


def profiles(request):
    profiles, search_query = searchProfiles(request)
    custom_range, profiles = paginateProfiles(request, profiles, 3)
    context = {'profiles': profiles, 'search_query': search_query,
               'custom_range': custom_range}
    return render(request, 'users/profiles.html', context)


def userProfile(request, pk):
    profile = Profile.objects.get(id=pk)
    topSkills = profile.skill_set.exclude(description__exact="")
    otherSkills = profile.skill_set.filter(description="")
    context = {'profile': profile,
               'topSkills': topSkills, 'otherSkills': otherSkills}
    return render(request, 'users/user_profile.html', context)


@login_required(login_url="users:login")
def userAccount(request):
    profile = request.user.profile
    skills = profile.skill_set.all()
    projects = profile.project_set.all()
    context = {'profile': profile, 'skills': skills, 'projects': projects}
    return render(request, 'users/account.html', context)


@login_required(login_url='users:login')
def editAccount(request):
    profile = request.user.profile
    form = ProfileForm(instance=profile)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('users:account')
    context = {'form': form}
    return render(request, 'users/profile_form.html', context)


@login_required(login_url='users:login')
def createSkill(request):
    profile = request.user.profile
    form = SkillForm()
    if request.method == "POST":
        form = SkillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.owner = profile
            skill.save()
            messages.success(request, 'Skill was added successfuly!')
            return redirect('users:account')
    context = {'form': form}
    return render(request, 'users/skill_form.html', context)


@login_required(login_url='users:login')
def updateSkill(request, pk):
    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)
    form = SkillForm(instance=skill)
    if request.method == "POST":
        form = SkillForm(request.POST, instance=skill)
        if form.is_valid():
            form.save()
            messages.success(request, 'Skill was updated successfuly!')
            return redirect('users:account')
    context = {'form': form}
    return render(request, 'users/skill_form.html', context)


@login_required(login_url='users:login')
def deleteSkill(request, pk):
    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)
    if request.method == "POST":
        skill.delete()
        messages.info(request, 'Successfuly deleted!')
        return redirect('users:account')
    context = {'object': skill}
    return render(request, 'delete_template.html', context)


@login_required(login_url='users:login')
def inbox(request):
    profile = request.user.profile
    messageRequests = profile.messages.all()
    unreadCount = messageRequests.filter(isRead=False).count()
    context = {'messageRequests': messageRequests, 'unreadCount': unreadCount}
    return render(request, 'users/inbox.html', context)


@login_required(login_url='users:login')
def viewMessage(request, pk):
    profile = request.user.profile
    message = profile.messages.get(id=pk)
    if message.isRead == False:
        message.isRead = True
        message.save()
    context = {'message': message}
    return render(request, 'users/message.html', context)


def createMessage(request, pk):
    recipient = Profile.objects.get(id=pk)
    form = MessageForm()
    try:
        sender = request.user.profile
    except:
        sender = None
    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = sender
            message.recipient = recipient

            if sender:
                message.name = sender.name
                message.email = sender.email
            message.save()

            messages.success(request, 'Your message was sent!')
            return redirect('users:user_profile', pk=recipient.id)
    context = {'recipient': recipient, 'form': form}
    return render(request, 'users/message_form.html', context)

users/templates/users/account.html
{% extends 'base.html' %}

{% block title %}Account{% endblock title %}

{% block content %}
<!-- Main Section -->
<main class="settingsPage profile my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="card__body dev">
            <a
              class="tag tag--pill tag--main settings__btn"
              href="{% url 'users:edit_account' %}"
              ><i class="im im-edit"></i> Edit</a
            >
            <img
              class="avatar avatar--xl dev__avatar"
              src="{{ profile.imageUrl }}"
            />
            <h2 class="dev__name">{{ profile.name }}</h2>
            <p class="dev__title">{{ profile.shortIntro }}</p>
            <p class="dev__location">Based in {{ profile.location }}</p>
            <ul class="dev__social">
              {% if profile.socialGithub %}
              <li>
                <a
                  title="Github"
                  href="{{ profile.socialGithub }}"
                  target="_blank"
                  ><i class="im im-github"></i
                ></a>
              </li>
              {% endif %} {% if profile.socialTwitter %}
              <li>
                <a
                  title="Twitter"
                  href="{{ profile.socialTwitter }}"
                  target="_blank"
                  ><i class="im im-twitter"></i
                ></a>
              </li>
              {% endif %} {% if profile.sociallinkedin %}
              <li>
                <a
                  title="LinkedIn"
                  href="{{ profile.sociallinkedin }}"
                  target="_blank"
                  ><i class="im im-linkedin"></i
                ></a>
              </li>
              {% endif %} {% if profile.socialWebsite %}
              <li>
                <a
                  title="Personal Website"
                  href="{{ profile.socialWebsite }}"
                  target="_blank"
                  ><i class="im im-globe"></i
                ></a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
      <div class="column column--2of3">
        <div class="devInfo">
          <h3 class="devInfo__title">About Me</h3>
          <p class="devInfo__about">{{ profile.bio|linebreaks }}</p>
        </div>
        <div class="settings">
          <h3 class="settings__title">Skills</h3>
          <a
            class="tag tag--pill tag--sub settings__btn tag--lg"
            href="{% url 'users:create_skill' %}"
            ><i class="im im-plus"></i> Add Skill</a
          >
        </div>

        <table class="settings__table">
          {% for skill in skills %}
          <tr>
            <td class="settings__tableInfo">
              <h4>{{ skill.name }}</h4>
              <p>{{ skill.description }}</p>
            </td>
            <td class="settings__tableActions">
              <a
                class="tag tag--pill tag--main settings__btn"
                href="{% url 'users:update_skill' skill.id %}"
                ><i class="im im-edit"></i> Edit</a
              >
              <a
                class="tag tag--pill tag--main settings__btn"
                href="{% url 'users:delete_skill' skill.id %}"
                ><i class="im im-x-mark-circle-o"></i> Delete</a
              >
            </td>
          </tr>
          {% endfor %}
        </table>

        <div class="settings">
          <h3 class="settings__title">Projects</h3>
          <a
            class="tag tag--pill tag--sub settings__btn tag--lg"
            href="{% url 'projects:create_project' %}"
            ><i class="im im-plus"></i> Add Project</a
          >
        </div>

        <table class="settings__table">
          {% for project in projects %}
          <tr>
            <td class="settings__thumbnail">
              <a href="{% url 'projects:project' project.id %}"
                ><img src="{{ project.imageUrl }}" alt="{{ porject.title }}"
              /></a>
            </td>
            <td class="settings__tableInfo">
              <a href="{% url 'projects:project' project.id %}"
                >{{ project.title }}</a
              >
              <p>{{ project.description|slice:'150' }}</p>
            </td>
            <td class="settings__tableActions">
              <a
                class="tag tag--pill tag--main settings__btn"
                href="{% url 'projects:update_project' project.id %}"
                ><i class="im im-edit"></i> Edit</a
              >
              <a
                class="tag tag--pill tag--main settings__btn"
                href="{% url 'projects:delete_project' project.id %}"
                ><i class="im im-x-mark-circle-o"></i> Delete</a
              >
            </td>
          </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

users/templates/users/inbox.html
{% extends 'base.html' %}

{% block title %}Inbox{% endblock title %}

{% block content %}
<!-- Main Section -->
<main class="inbox my-xl">
  <div class="content-box">
    <h3 class="inbox__title">New Messages(<span>{{ unreadCount }}</span>)</h3>
    <ul class="messages">
      {% for message in messageRequests %}
        {% if message.isRead == False %}
        <li class="message message--unread">{% else %}</li>

        <li class="message">
        {% endif %}
          <a href="{% url 'users:view_message' message.id %}">
            <span class="message__author">{{ message.name }}</span>
            <span class="message__subject">{{ message.subject }}</span>
            <span class="message__date">{{ message.created }}</span>
          </a>
        </li>
      {% endfor %}
    </ul>
  </div>
</main>
{% endblock content %}

users/templates/users/login_register.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Authentication{%endblock title %}

{% block content %} 
  {% if page == 'register' %}
  <div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="{% static 'images/icon.svg' %}" alt="icon" />
        </a>
        <h3>Account SignUp</h3>
        <p>Create a new developer account</p>
      </div>

      <form
        action="{% url 'users:register' %}"
        method="post"
        class="form auth__form"
      >
        {% csrf_token %} 
        {% for field in form %}
          <div class="form__field">
            <label for="formInput#text">{{ field.label }}: </label>
            {{ field }} {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}

        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Sign In" />
        </div>
      </form>
      <div class="auth__alternative">
        <p>Already have an Account?</p>
        <a href="{% url 'users:login' %}">Log In</a>
      </div>
    </div>
  </div>
  {% else %}
    <div class="auth">
      <div class="card">
        <div class="auth__header text-center">
          <a href="/">
            <img src="{% static 'images/icon.svg' %}" alt="icon" />
          </a>
          <h3>Account Login</h3>
          <p>Hello Developer, Welcome Back!</p>
        </div>

        <form action="" method="post" class="form auth__form">
          {% csrf_token %}
          <!-- Input:Username -->
          <div class="form__field">
            <label for="formInput#text">Username: </label>
            <input
              class="input input--text"
              id="formInput#text"
              type="text"
              name="username"
              placeholder="Enter your username..."
            />
          </div>

          <!-- Input:Password -->
          <div class="form__field">
            <label for="formInput#password">Password: </label>
            <input
              class="input input--password"
              id="formInput#passowrd"
              type="password"
              name="password"
              placeholder="••••••••"
            />
          </div>
          <div class="auth__actions">
            <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
            <a href="{% url 'reset_password' %}">Forget Password?</a>
          </div>
        </form>
        <div class="auth__alternative">
          <p>Don’t have an Account?</p>
          <a href="{% url 'users:register' %}">Sign Up</a>
        </div>
      </div>
    </div>
  {% endif %} 
{% endblock content %}

users/templates/users/message.html
{% extends 'base.html' %} 

{% block title %}Message{% endblock title %}

{% block content %}
<!-- Main Section -->
<main class="messagePage my-xl">
  <div class="content-box">
    <div class="message">
      <a class="backButton" href="{% url 'users:inbox' %}"
        ><i class="im im-angle-left"></i
      ></a>
      <h2 class="message__subject">{{ message.subject }}</h2>
      {% if message.sender %}
      <a
        href="{% url 'users:user_profile' message.sender.id %}"
        class="message__author"
        >{{ message.name }}</a
      >
      {% else %}
      <p class="message__author">{{ message.name }}</p>
      {% endif %}

      <p class="message__date">{{ message.created }}</p>
      <div class="message__body">{{ message.body|linebreaks }}</div>
    </div>
  </div>
</main>
{% endblock content %}

users/templates/users/user_profile.html
{% extends 'base.html' %}

{% block title %}{{ profile.name }}{% endblock title%}

{%block content %}
<!-- Main Section -->
<main class="profile my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="card__body dev">
            <img class="avatar avatar--xl" src="{{ profile.imageUrl }}" />
            <h2 class="dev__name">{{ profile.name }}</h2>
            <p class="dev__title">{{ profile.shortIntro }}</p>
            <p class="dev__location">Based in {{ profile.location }}</p>
            <ul class="dev__social">
              {% if profile.socialGithub %}
              <li>
                <a
                  title="Github"
                  href="{{ profile.socialGithub }}"
                  target="_blank"
                  ><i class="im im-github"></i
                ></a>
              </li>
              {% endif %} {% if profile.socialTwitter %}
              <li>
                <a
                  title="Twitter"
                  href="{{ profile.socialTwitter }}"
                  target="_blank"
                  ><i class="im im-twitter"></i
                ></a>
              </li>
              {% endif %} {% if profile.sociallinkedin %}
              <li>
                <a
                  title="LinkedIn"
                  href="{{ profile.sociallinkedin }}"
                  target="_blank"
                  ><i class="im im-linkedin"></i
                ></a>
              </li>
              {% endif %} {% if profile.socialWebsite %}
              <li>
                <a
                  title="Personal Website"
                  href="{{ profile.socialWebsite }}"
                  target="_blank"
                  ><i class="im im-globe"></i
                ></a>
              </li>
              {% endif %}
            </ul>
            {% if request.user.profile.id != profile.id %}
            <a
              href="{% url 'users:create_message' profile.id %}"
              class="btn btn--sub btn--lg"
              >Send Message
            </a>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="column column--2of3">
        <div class="devInfo">
          <h3 class="devInfo__title">About Me</h3>
          <p class="devInfo__about">{{ profile.bio|linebreaks }}</p>
        </div>
        <div class="devInfo">
          <h3 class="devInfo__title">Skills</h3>
          <div class="devInfo__skills">
            {% for skill in topSkills %}
            <div class="devSkill">
              <h4 class="devSkill__title">{{ skill.name }}</h4>
              <p class="devSkill__info">{{ skill.description }}</p>
            </div>
            {% endfor %}

            <h3 class="devInfo__subtitle">Other Skills</h3>
            <div class="devInfo__otherSkills">
              {% for skill in otherSkills %}
              <span class="tag tag--pill tag--sub tag--lg">
                <small>{{ skill.name }}</small>
              </span>
              {% endfor %}
            </div>
          </div>
        </div>
        <div class="devInfo">
          <h3 class="devInfo__title">Projects</h3>
          <div class="grid grid--two">
            {% for project in profile.project_set.all %}
            <div class="column">
              <div class="card project">
                <a
                  href="{% url 'projects:project' project.id %}"
                  class="project"
                >
                  <img
                    class="project__thumbnail"
                    src="{{ project.imageUrl }}"
                    alt="project thumbnail"
                  />
                  <div class="card__body">
                    <h3 class="project__title">{{ project.title }}</h3>
                    <p>
                      <a
                        class="project__author"
                        href="{% url 'users:user_profile' project.owner.id %}"
                        >By {{ project.owner.name }}</a
                      >
                    </p>
                    <p class="project--rating">
                      <span style="font-weight: bold"
                        >{{ project.voteRatio }}%</span
                      >
                      Postitive Feedback ({{ project.voteTotal }} Vote{{
                      project.voteTotal|pluralize:'s' }})
                    </p>
                    <div class="project__tags">
                      {% for tag in project.tags.all %}
                      <span class="tag tag--pill tag--main">
                        <small>{{ tag }}</small>
                      </span>
                      {% endfor %}
                    </div>
                  </div>
                </a>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}