api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView)
from . import views


app_name = 'api'

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(),
         name='token_refresh'),
    path('', views.getRoutes, name='routes'),
    path('projects/', views.getProjects, name='projects'),
    path('projects/<int:pk>/', views.getProject, name='project'),
    path('projects/<int:pk>/vote/', views.projectVote, name='project_vote'),
    path('removetag/', views.removeTag, name='remove_tag'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls', namespace='projects')),
    path('', include('users.urls', namespace='users')),
    path('api/', include('api.urls', namespace='api')),
    path('reset_password/',
         auth_views.PasswordResetView.as_view(
             template_name='reset_password.html'),
         name='reset_password'),
    path('reset_password_sent/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name='reset_password_sent.html'),
         name='passowrd_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='reset.html'),
         name='passowrd_reset_confirm'),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='passowrd_reset_complete.html'),
         name='passowrd_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from . import views


app_name = 'projects'

urlpatterns = [
    path('', views.projects, name='projects'),
    path('project/<str:pk>/', views.project, name='project'),
    path('create/', views.createProject, name='create_project'),
    path('update/<str:pk>/',
         views.updateProject, name='update_project'),
    path('delete/<str:pk>/',
         views.deleteProject, name='delete_project'),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>/', views.userProfile, name='user_profile'),
    path('register/', views.registerUser, name='register'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('account/', views.userAccount, name='account'),
    path('edit/', views.editAccount, name='edit_account'),
    path('create/skill/', views.createSkill, name='create_skill'),
    path('update/skill/<str:pk>/', views.updateSkill, name='update_skill'),
    path('delete/skill/<str:pk>/', views.deleteSkill, name='delete_skill'),
    path('inbox/', views.inbox, name='inbox'),
    path('message/<str:pk>/', views.viewMessage, name='view_message'),
    path('create/message/<str:pk>/', views.createMessage,
         name='create_message'),
]

projects/models.py
import uuid
from django.db import models
from users.models import Profile


class Project(models.Model):
    owner = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(
        upload_to='project/%Y/', default='default.jpg', null=True, blank=True)
    demoLink = models.CharField(max_length=2000, null=True, blank=True)
    sourceLink = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    voteTotal = models.IntegerField(default=0, null=True, blank=True)
    voteRatio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    class Meta:
        ordering = ('-voteRatio', '-voteTotal', 'title')

    def __str__(self):
        return self.title

    @property
    def imageUrl(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list('owner__id', flat=True)
        return queryset

    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()

        ratio = (upVotes / totalVotes) * 100
        self.voteTotal = totalVotes
        self.voteRatio = ratio

        self.save()


class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote')
    )
    owner = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    class Meta:
        unique_together = [['owner', 'project']]

    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.name
        return self.name

projects/forms.py
from django.forms import ModelForm
from django import forms
from .models import Project, Review


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ('title', 'description', 'image', 'demoLink',
                  'sourceLink')
        widgets = {
            'tags': forms.CheckboxSelectMultiple()
        }

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ('value', 'body')
        labels = {
            'value': 'Place Your vote',
            'body': 'Add a comment with your vote'
        }

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

projects/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Project, Tag
from .forms import ProjectForm, ReviewForm
from .utils import searchProjects, paginateProjects


def projects(request):
    projects, search_query = searchProjects(request)
    custom_range, projects = paginateProjects(request, projects, 3)
    context = {'projects': projects, 'search_query': search_query,
               'custom_range': custom_range}
    return render(request, 'projects/projects.html', context)


def project(request, pk):
    project = Project.objects.get(id=pk)
    form = ReviewForm()

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        review = form.save(commit=False)
        review.project = project
        review.owner = request.user.profile
        review.save()

        project.getVoteCount

        messages.success(request, 'Your review was successfully submitted!')
        return redirect('projects:project', pk=project.id)
    context = {'project': project, 'form': form}
    return render(request, 'projects/single_project.html', context)


@login_required(login_url="users:login")
def createProject(request):
    profile = request.user.profile
    form = ProjectForm()
    if request.method == 'POST':
        newtags = request.POST.get('newtags').replace(',', ' ').split()
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            project = form.save(commit=False)
            project.owner = profile
            project.save()
            for tag in newtags:
                tag, created = Tag.objects.get_or_create(name=tag)
                project.tags.add(tag)
            return redirect('users:account')
    context = {'form': form}
    return render(request, 'projects/project_form.html', context)


@login_required(login_url="users:login")
def updateProject(request, pk):
    profile = request.user.profile
    project = profile.project_set.get(id=pk)
    form = ProjectForm(instance=project)
    if request.method == 'POST':
        newtags = request.POST.get('newtags').replace(',', ' ').split()
        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            project = form.save()
            for tag in newtags:
                tag, created = Tag.objects.get_or_create(name=tag)
                project.tags.add(tag)
            return redirect('users:account')
    context = {'form': form, 'project': project}
    return render(request, 'projects/project_form.html', context)


@login_required(login_url="users:login")
def deleteProject(request, pk):
    profile = request.user.profile
    project = profile.project_set.get(id=pk)
    if request.method == 'POST':
        project.delete()
        return redirect('users:account')
    context = {'object': project}
    return render(request, 'delete_template.html', context)

projects/templates/projects/project_form.html
{% extends 'base.html' %}

{% block title %}Add Project{% endblock title %}

{%block content %}
<!-- Main Section -->
<main class="formPage my-xl">
  <div class="content-box">
    <div class="formWrapper">
      <a class="backButton" href="{% url 'projects:projects' %}"
        ><i class="im im-angle-left"></i
      ></a>
      <br />

      <form class="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %} 
        {% for field in form %}
          <!-- Input:Text -->
          <div class="form__field">
            <label for="formInput#text">{{ field.label }}</label>
            {{ field }}
          </div>
        {% endfor %}

        <div class="form__field">
          {% for tag in project.tags.all %}
          <div
            class="project-tag tag tag--pill tag--main"
            data-tag="{{tag.id}}"
            data-project="{{project.id}}"
          >
            {{tag.name}} &#215;
          </div>
          {% endfor %}
        </div>

        <div class="form__field">
          <label for="formInput#text">Tags</label>
          <textarea
            class="input"
            name="newtags"
            placeholder="Add tags here..."
          ></textarea>
        </div>

        <input
          class="btn btn--sub btn--lg my-md"
          type="submit"
          value="Submit"
        />
      </form>
    </div>
  </div>
</main>
{% endblock content %}

projects/templates/projects/projects.html
{% extends 'base.html' %}

{% block title %}Projects{% endblock title %}

{% block content %}
<!-- Main Section -->
<main class="projects">
  <section class="hero-section text-center">
    <div class="container container--narrow">
      <div class="hero-section__box">
        <h2>Search for <span>Projects</span></h2>
      </div>

      <div class="hero-section__search">
        <form
          id="searchForm"
          class="form"
          action="{% url 'projects:projects' %}"
          method="get"
        >
          <div class="form__field">
            <label for="formInput#search">Search By Projects </label>
            <input
              class="input input--text"
              id="formInput#search"
              type="text"
              name="search_query"
              value="{{ search_query }}"
              placeholder="Search by Project Title"
            />
          </div>

          <input class="btn btn--sub btn--lg" type="submit" value="Search" />
        </form>
      </div>
    </div>
  </section>
  <!-- Search Result: DevList -->
  <section class="projectsList">
    <div class="container">
      <div class="grid grid--three">
        {% for project in projects %}
          <div class="column">
            <div class="card project">
              <a href="{% url 'projects:project' project.pk %}" class="project">
                <img
                  class="project__thumbnail"
                  src="{{ project.imageUrl }}"
                  alt="project thumbnail"
                />
                <div class="card__body">
                  <h3 class="project__title">{{ project.title }}</h3>
                  <p>
                    <a
                      class="project__author"
                      href="{% url 'users:user_profile' project.owner.id %}"
                      >By {{ project.owner.name }}</a
                    >
                  </p>
                  <p class="project--rating">
                    <span style="font-weight: bold"
                      >{{ project.voteRatio }}%</span
                    >
                    Positive Feedback ({{ project.voteTotal }}) Vote{{
                    project.voteTotal|pluralize:"s" }}
                  </p>
                  <div class="project__tags">
                    {% for tag in project.tags.all %}
                      <span class="tag tag--pill tag--main">
                        <small>{{ tag }}</small>
                      </span>
                    {% endfor %}
                  </div>
                </div>
              </a>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>
  {% include 'pagination.html' with queryset=projects custom_range=custom_range%}
</main>
{% endblock content %}

projects/templates/projects/single-project.html
{% extends 'base.html' %}

{% block title %}Single Projects{% endblock title %}

{% block content %}

{% endblock content %}

projects/templates/projects/single_project.html
{% extends 'base.html' %}

{% block title %}{{ project.title }}{% endblock title%}

{% block content %}
<!-- Main Section -->
<main class="singleProject my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <h3 class="singleProject__subtitle">Tools & Stacks</h3>
        <div class="singleProject__toolStack">
          {% for tag in project.tags.all %}
            <span class="tag tag--pill tag--sub tag--lg">
                <small>{{tag}}</small>
            </span>
          {% endfor %}
        </div>

        {% if project.sourceLink %}
            <a
            class="singleProject__liveLink"
            href="{{project.sourceLink}}"
            target="_blank"
            ><i class="im im-external-link"></i>Source Code
            </a>
        {% endif %}
        {% if project.demoLink %}
            <a
            class="singleProject__liveLink"
            href="{{project.demoLink}}"
            target="_blank"
            ><i class="im im-external-link"></i>Live Demo
            </a>
        {% endif %}
      </div>
      <div class="column column--2of3">
        <img
          class="singleProject__preview"
          src="{{ project.imageUrl }}"
          alt="portfolio thumbnail"
        />
        <a
          href="{% url 'users:user_profile' project.owner.id  %}"
          class="singleProject__developer"
          >{{project.owner.name}}</a
        >
        <h2 class="singleProject__title">{{project.title}}</h2>
        <h3 class="singleProject__subtitle">About the Project</h3>
        <div class="singleProject__info">{{project.description}}</div>
        <div class="comments">
          <h3 class="singleProject__subtitle">Feedback</h3>
          <h5 class="project--rating">
            {{project.vote_ratio}}% Positive Feedback ({{project.vote_total}}
            Vote{{project.vote_total|pluralize:"s"}})
          </h5>

          {% if request.user.profile.id in project.reviewers %}
            <p>You have already submitted your review for this project</p>

          {% elif request.user.profile == project.owner %}
            <p>You cannot review your own work</p>

          {% elif request.user.is_authenticated %}
            <form
                class="form"
                action="{% url 'projects:project' project.id %}"
                method="POST"
            >
                {% csrf_token %} {% for field in form %}
                <div class="form__field">
                <label for="formInput#textarea">{{field.label}}</label>
                {{field}}
                </div>
                {% endfor %}
                <input
                class="btn btn--sub btn--lg"
                type="submit"
                value="Add Review"
                />
            </form>
          {% else %}
            <a href="{% url 'users:login' %}?next={{request.path}}"
                >Please login to leave a review</a
            >
          {% endif %}

          <div class="commentList">
            {% for review in project.review_set.all %} 
                {% if review.body %}
                    <div class="comment">
                    <a href="{% url 'users:user_profile' review.owner.id  %}">
                        <img
                        class="avatar avatar--md"
                        src="{{review.owner.image.url}}"
                        alt="user"
                        />
                    </a>

                    <div class="comment__details">
                        <a
                        href="{% url 'users:user_profile' review.owner.id  %}"
                        class="comment__author"
                        >{{review.owner.name}}</a
                        >
                        <p class="comment__info">{{review.body|linebreaksbr}}</p>
                    </div>
                    </div>
                {% endif %}
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

{% endblock %}