api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView)
from . import views


app_name = 'api'

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(),
         name='token_refresh'),
    path('', views.getRoutes, name='routes'),
    path('projects/', views.getProjects, name='projects'),
    path('projects/<int:pk>/', views.getProject, name='project'),
    path('projects/<int:pk>/vote/', views.projectVote, name='project_vote'),
    path('removetag/', views.removeTag, name='remove_tag'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls', namespace='projects')),
    path('', include('users.urls', namespace='users')),
    path('api/', include('api.urls', namespace='api')),
    path('reset_password/',
         auth_views.PasswordResetView.as_view(
             template_name='reset_password.html'),
         name='reset_password'),
    path('reset_password_sent/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name='reset_password_sent.html'),
         name='passowrd_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='reset.html'),
         name='passowrd_reset_confirm'),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='passowrd_reset_complete.html'),
         name='passowrd_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>/', views.userProfile, name='user_profile'),
    path('register/', views.registerUser, name='register'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('account/', views.userAccount, name='account'),
    path('edit/', views.editAccount, name='edit_account'),
    path('create/skill/', views.createSkill, name='create_skill'),
    path('update/skill/<str:pk>/', views.updateSkill, name='update_skill'),
    path('delete/skill/<str:pk>/', views.deleteSkill, name='delete_skill'),
    path('inbox/', views.inbox, name='inbox'),
    path('message/<str:pk>/', views.viewMessage, name='view_message'),
    path('create/message/<str:pk>/', views.createMessage,
         name='create_message'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Favicon -->
    <link
      rel="shortcut icon"
      href="{% static 'images/favicon.ico' %}"
      type="image/x-icon"
    />
    <!-- Icon - IconMonster -->
    <link
      rel="stylesheet"
      href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css"
    />
    <!-- Mumble UI -->
    <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="{% static 'styles/app.css' %}" />

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    {% include 'messages.html' %}
    {% block content%}{% endblock content %}

    <script src="{% static 'uikit/app.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/delete_template.html
{% extends 'base.html' %}

{% block title %}Delete{% endblock title %}

{% block content %}
<!-- Main Section -->
<main class="formPage my-xl">
  <div class="content-box">
    <div class="formWrapper">
      <a class="backButton" href="{% url 'users:account' %}"
        ><i class="im im-angle-left"></i
      ></a>
      <br />
      <form class="form" method="POST">
        {% csrf_token %}
        <p>Are your sure you want to delete this "{{ object }}"?</p>
        <a class="btn btn--sub btn--lg my-md" href="{% url 'users:account' %}"
          >Go Back</a
        >
        <input
          class="btn btn--sub btn--lg my-md"
          type="submit"
          value="Delete"
        />
      </form>
    </div>
  </div>
</main>
{% endblock content %}

templates/messages.html
{% if messages %} 
  {% for message in messages %}
    <div class="alert alert--{{ message.tags }}">
      <p class="alert__message">{{ message }}</p>
      <button class="alert__close">x</button>
    </div>
  {% endfor %}
{% endif %}

templates/navbar.html
{% load static %}

<!-- Header Section -->
<header class="header">
  <div class="container container--narrow">
    <a href="{% url 'users:profiles' %}" class="header__logo">
      <img src="{% static 'images/logo.svg' %}" alt="DevSearch Logo" />
    </a>
    <nav class="header__nav">
      <input type="checkbox" id="responsive-menu" />
      <label for="responsive-menu" class="toggle-menu">
        <span>Menu</span>
        <div class="toggle-menu__lines"></div>
      </label>
      <ul class="header__menu">
        <li class="header__menuItem">
          <a href="{% url 'users:profiles' %}">Developers</a>
        </li>
        <li class="header__menuItem">
          <a href="{% url 'projects:projects' %}">Projects</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="header__menuItem">
          <a href="{% url 'users:inbox' %}">Inbox</a>
        </li>
        <li class="header__menuItem">
          <a href="{% url 'users:account' %}">Account</a>
        </li>
        <li class="header__menuItem">
          <a href="{% url 'users:logout' %}" class="btn btn--sub">Logout</a>
        </li>
        {% else %}
        <li class="header__menuItem">
          <a href="{% url 'users:login' %}" class="btn btn--sub"
            >Login/Sign Up</a
          >
        </li>
        {% endif %}
      </ul>
    </nav>
  </div>
</header>

templates/pagination.html
{% if queryset.has_other_pages %}
<div class="pagination">
  <ul class="container">
    {% if queryset.has_previous %}
      <li>
        <a
          href="?page={{ queryset.previous_page_number }}"
          class="btn page-link"
          data-page="{{queryset.previous_page_number}}"
          >&#10094; Prev</a
        >
      </li>
    {% endif %}
    {% for page in custom_range %}
      {% if page == queryset.number %}
        <li>
          <a
            href="?page={{ page }}"
            class="btn page-link btn--sub"
            data-page="{{page}}"
            >{{ page }}</a
          >
        </li>
      {% else %}
        <li>
          <a href="?page={{ page }}" class="btn page-link" data-page="{{page}}"
            >{{ page }}</a
          >
        </li>
      {% endif %}
    {% endfor %}
    {% if queryset.has_next %}
      <li>
        <a
          href="?page={{ queryset.next_page_number }}"
          class="btn page-link"
          data-page="{{queryset.next_page_number}}"
          >Next &#10095;</a
        >
      </li>
    {% endif %}
  </ul>
</div>
{% endif %}

templates/passowrd_reset_complete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Reset Password Complete{% endblock title %}

{% block content %}
<div class="auth">
  <div class="card">
    <div class="auth__header text-center">
      <a href="/">
        <img src="{% static 'images/icon.svg' %}" alt="icon" />
      </a>
      <h3>Forget Password Complete</h3>
      <p>Your password has been set. You may go ahead and log in now.</p>
      <br />
      <a href="{% url 'users:login' %}">Login</a>
    </div>
  </div>
</div>
{% endblock content %}

templates/reset.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Reset Password{%endblock title %}

{% block content %}
<div class="auth">
  <div class="card">
    <div class="auth__header text-center">
      <a href="/">
        <img src="{% static 'images/icon.svg' %}" alt="icon" />
      </a>
      <h3>Enter New Password</h3>
      <p>
        Please enter your new password twice so we can verify you typed it in
        correctly.
      </p>
    </div>

    <form action="" class="form auth__form" method="post">
      {% csrf_token %}
      <!-- Input:Email -->
      <div class="form__field">{{ form.as_p }}</div>
    </form>
  </div>
</div>
{% endblock content %}

templates/reset_password.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Reset Password Request{% endblock title %}

{% block content %}
<div class="auth">
  <div class="card">
    <div class="auth__header text-center">
      <a href="/">
        <img src="{% static 'images/icon.svg' %}" alt="icon" />
      </a>
      <h3>Forget Password?</h3>
      <p>Reset password by entering the email address</p>
    </div>

    <form action="#" class="form auth__form" method="post">
      {% csrf_token %}

      <!-- Input:Email -->
      <div class="form__field">{{ form.as_p }}</div>

      <div class="auth__actions">
        <input class="btn btn--sub btn--lg" type="submit" value="Send Email" />
        <a href="{% url 'users:login' %}">Login</a>
      </div>
    </form>
    <div class="auth__alternative">
      <p>Don’t have an Account?</p>
      <a href="{% url 'users:register' %}">Sign Up</a>
    </div>
  </div>
</div>
{% endblock content %}

templates/reset_password_sent.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Reset Password Sent{% endblock title %}

{% block content %}
<div class="auth">
  <div class="card">
    <div class="auth__header text-center">
      <a href="/">
        <img src="{% static 'images/icon.svg' %}" alt="icon" />
      </a>
      <h3>Forget Password Sent</h3>
      <p>
        We’ve emailed you instructions for setting your password, if an account
        exists with the email you entered. You should receive them shortly.
      </p>
      <br />
      <p>
        If you don’t receive an email, please make sure you’ve entered the
        address you registered with, and check your spam folder.
      </p>
    </div>
  </div>
</div>
{% endblock content %}